class_name GameResources
extends RefCounted
## Resource type constants and storage for an empire.

enum ResourceType {
	ENERGY,
	MINERALS,
	FOOD,
	ALLOYS,
	RESEARCH,
	CONSUMER_GOODS,
	INFLUENCE,
	UNITY,
	TRADE,
	VOLATILE_MOTES,
	EXOTIC_GASES,
	RARE_CRYSTALS,
	LIVING_METAL,
	DARK_MATTER,
	ZRO,
	# Raw (PDF Tier 1)
	GAS,
	ICE,
	BIOMASS,
	# Refined (PDF Tier 2)
	FUEL_CELLS,
	SYNTHETICS,
	PHARMACEUTICALS,
	# Strategic (PDF Tier 3)
	STELLITE,
	VOID_GAS,
	NANITE_DUST,
	PSIONIC_ORE,
	DARK_LATTICE,
	# Abstract
	COMMAND_POINTS,
	COGNITION,
	MANPOWER,
	LAST
}

const RESOURCE_NAMES: Dictionary = {
	ResourceType.ENERGY: "Energy",
	ResourceType.MINERALS: "Minerals",
	ResourceType.FOOD: "Food",
	ResourceType.ALLOYS: "Alloys",
	ResourceType.RESEARCH: "Research",
	ResourceType.CONSUMER_GOODS: "Consumer Goods",
	ResourceType.INFLUENCE: "Influence",
	ResourceType.UNITY: "Unity",
	ResourceType.TRADE: "Trade",
	ResourceType.VOLATILE_MOTES: "Volatile Motes",
	ResourceType.EXOTIC_GASES: "Exotic Gases",
	ResourceType.RARE_CRYSTALS: "Rare Crystals",
	ResourceType.LIVING_METAL: "Super Tensiles",
	ResourceType.DARK_MATTER: "Dark Matter",
	ResourceType.ZRO: "Zro",
	ResourceType.GAS: "Gas",
	ResourceType.ICE: "Ice",
	ResourceType.BIOMASS: "Biomass",
	ResourceType.FUEL_CELLS: "Fuel Cells",
	ResourceType.SYNTHETICS: "Synthetics",
	ResourceType.PHARMACEUTICALS: "Pharmaceuticals",
	ResourceType.STELLITE: "Stellite",
	ResourceType.VOID_GAS: "Void Gas",
	ResourceType.NANITE_DUST: "Nanite Dust",
	ResourceType.PSIONIC_ORE: "Psionic Ore",
	ResourceType.DARK_LATTICE: "Dark Lattice",
	ResourceType.COMMAND_POINTS: "Command Points",
	ResourceType.COGNITION: "Cognition",
	ResourceType.MANPOWER: "Manpower",
}

## Short names for top bar (e.g. E, M, F).
const RESOURCE_SHORT_NAMES: Dictionary = {
	ResourceType.ENERGY: "E",
	ResourceType.MINERALS: "M",
	ResourceType.FOOD: "F",
	ResourceType.ALLOYS: "A",
	ResourceType.RESEARCH: "R",
	ResourceType.CONSUMER_GOODS: "CG",
	ResourceType.INFLUENCE: "I",
	ResourceType.UNITY: "U",
	ResourceType.TRADE: "T",
	ResourceType.VOLATILE_MOTES: "VM",
	ResourceType.EXOTIC_GASES: "EG",
	ResourceType.RARE_CRYSTALS: "RC",
	ResourceType.LIVING_METAL: "ST",
	ResourceType.DARK_MATTER: "DM",
	ResourceType.ZRO: "Zro",
	ResourceType.GAS: "Gas",
	ResourceType.ICE: "Ice",
	ResourceType.BIOMASS: "Bio",
	ResourceType.FUEL_CELLS: "FC",
	ResourceType.SYNTHETICS: "Syn",
	ResourceType.PHARMACEUTICALS: "Pharm",
	ResourceType.STELLITE: "Stel",
	ResourceType.VOID_GAS: "VG",
	ResourceType.NANITE_DUST: "ND",
	ResourceType.PSIONIC_ORE: "Psi",
	ResourceType.DARK_LATTICE: "DL",
	ResourceType.COMMAND_POINTS: "CP",
	ResourceType.COGNITION: "Cog",
	ResourceType.MANPOWER: "MP",
}

## Icon color per resource for top-bar indicators (readable on dark UI).
const RESOURCE_ICON_COLORS: Dictionary = {
	ResourceType.ENERGY: Color(1.0, 0.9, 0.2),
	ResourceType.MINERALS: Color(0.75, 0.6, 0.35),
	ResourceType.FOOD: Color(0.4, 0.85, 0.35),
	ResourceType.ALLOYS: Color(0.6, 0.6, 0.65),
	ResourceType.RESEARCH: Color(0.4, 0.7, 1.0),
	ResourceType.CONSUMER_GOODS: Color(0.6, 0.8, 0.95),
	ResourceType.INFLUENCE: Color(0.7, 0.5, 0.95),
	ResourceType.UNITY: Color(0.35, 0.85, 0.6),
	ResourceType.TRADE: Color(0.95, 0.75, 0.4),
	ResourceType.VOLATILE_MOTES: Color(0.95, 0.5, 0.3),
	ResourceType.EXOTIC_GASES: Color(0.5, 0.85, 0.95),
	ResourceType.RARE_CRYSTALS: Color(0.4, 0.9, 0.7),
	ResourceType.LIVING_METAL: Color(0.9, 0.7, 0.5),
	ResourceType.DARK_MATTER: Color(0.25, 0.2, 0.4),
	ResourceType.ZRO: Color(0.85, 0.6, 0.95),
	ResourceType.GAS: Color(0.55, 0.82, 0.95),
	ResourceType.ICE: Color(0.7, 0.9, 1.0),
	ResourceType.BIOMASS: Color(0.45, 0.75, 0.4),
	ResourceType.FUEL_CELLS: Color(0.95, 0.65, 0.25),
	ResourceType.SYNTHETICS: Color(0.65, 0.7, 0.8),
	ResourceType.PHARMACEUTICALS: Color(0.9, 0.75, 0.85),
	ResourceType.STELLITE: Color(0.5, 0.85, 0.7),
	ResourceType.VOID_GAS: Color(0.35, 0.25, 0.5),
	ResourceType.NANITE_DUST: Color(0.6, 0.95, 0.9),
	ResourceType.PSIONIC_ORE: Color(0.9, 0.6, 1.0),
	ResourceType.DARK_LATTICE: Color(0.15, 0.1, 0.25),
	ResourceType.COMMAND_POINTS: Color(0.5, 0.7, 0.95),
	ResourceType.COGNITION: Color(0.95, 0.85, 0.5),
	ResourceType.MANPOWER: Color(0.85, 0.5, 0.4),
}

## Tooltip descriptions for resource hover (from design doc).
const RESOURCE_DESCRIPTIONS: Dictionary = {
	ResourceType.ENERGY: "Universal currency; powers all upkeep and trade. Generated by trade routes, energy deposits, and taxation.",
	ResourceType.MINERALS: "Base mineral matter (ore); everything is built from it. Gathered from rocky planets and asteroid belts.",
	ResourceType.FOOD: "Feeds populations. Produced from fertile and ocean worlds.",
	ResourceType.ALLOYS: "Structural metal for ships, stations, and buildings. Produced from Ore + Gas at industrial facilities.",
	ResourceType.RESEARCH: "Advances technology across Physical, Social, and Xenological branches. Produced by researchers.",
	ResourceType.CONSUMER_GOODS: "Standard of living for pops; consumed monthly per pop. Shortfall causes happiness decay.",
	ResourceType.INFLUENCE: "Political capital; spent on claims, edicts, envoys, and policies. Slow to regenerate.",
	ResourceType.UNITY: "Cultural cohesion; advances the tradition tree and empire-wide bonuses. From happy pops and monuments.",
	ResourceType.TRADE: "Trade value from trade routes; converted to Energy by trade policy.",
	ResourceType.VOLATILE_MOTES: "Volatile compounds used in advanced industry and weapons.",
	ResourceType.EXOTIC_GASES: "Rare atmospheric compounds for life support and propulsion.",
	ResourceType.RARE_CRYSTALS: "Crystalline materials for electronics and advanced components.",
	ResourceType.LIVING_METAL: "Super-tensile exotic material for high-tier construction.",
	ResourceType.DARK_MATTER: "Exotic matter for advanced propulsion and megastructures.",
	ResourceType.ZRO: "Psionic resonance mineral; used in psionic tech and buildings.",
	ResourceType.GAS: "Atmospheric extraction; used in life support and propulsion. From gas giants and nebulae.",
	ResourceType.ICE: "Frozen volatiles; water and hydrogen compounds. From ice worlds and comet fields. Converts to Fuel Cells.",
	ResourceType.BIOMASS: "Organic matter; feeds populations and fuels biopharma. From fertile and ocean worlds.",
	ResourceType.FUEL_CELLS: "Powers ships, starbases, and orbital platforms. Deficit causes fleet attrition.",
	ResourceType.SYNTHETICS: "Machine parts, robotics, electronics. Produced from Ore + Energy.",
	ResourceType.PHARMACEUTICALS: "Population health and longevity. Shortfall reduces growth and habitability tolerance.",
	ResourceType.STELLITE: "Exotic crystalline metal; exceptional tensile strength. For Tier-3 hulls and megastructure frames.",
	ResourceType.VOID_GAS: "Gaseous dark matter residue; consumed by warp drives and jump tech.",
	ResourceType.NANITE_DUST: "Semi-sentient nanoscale machines. From ancient ruins; enables self-repair and augmentation.",
	ResourceType.PSIONIC_ORE: "Mineral with psionic properties. Unlocks psionic buildings and ship components.",
	ResourceType.DARK_LATTICE: "Crystallized dark energy; endgame capstone. For megastructures and ascension paths.",
	ResourceType.COMMAND_POINTS: "Fleet capacity; consumed by ship count. Hard cap on fleet size.",
	ResourceType.COGNITION: "Beyond conventional research; from Matrioshka Brains and psionic ascension. For transcendence projects.",
	ResourceType.MANPOWER: "Military personnel pool; generated from food and soldier jobs. Used for ship crews and planetary garrisons. Capped by empire size.",
}

## Top-bar sections: name and resource types. Row 1: Raw, Refined. Row 2: Strategic, Abstract.
const RESOURCE_SECTIONS_ROW1: Array[Dictionary] = [
	{ "name": "Raw", "types": [ResourceType.MINERALS, ResourceType.FOOD, ResourceType.GAS, ResourceType.ICE, ResourceType.BIOMASS] },
	{ "name": "Refined", "types": [ResourceType.ALLOYS, ResourceType.FUEL_CELLS, ResourceType.SYNTHETICS, ResourceType.PHARMACEUTICALS, ResourceType.CONSUMER_GOODS] },
]
const RESOURCE_SECTIONS_ROW2: Array[Dictionary] = [
	{ "name": "Strategic", "types": [ResourceType.VOLATILE_MOTES, ResourceType.EXOTIC_GASES, ResourceType.RARE_CRYSTALS, ResourceType.LIVING_METAL, ResourceType.DARK_MATTER, ResourceType.ZRO, ResourceType.STELLITE, ResourceType.VOID_GAS, ResourceType.NANITE_DUST, ResourceType.PSIONIC_ORE, ResourceType.DARK_LATTICE] },
	{ "name": "Abstract", "types": [ResourceType.ENERGY, ResourceType.RESEARCH, ResourceType.INFLUENCE, ResourceType.UNITY, ResourceType.TRADE, ResourceType.COMMAND_POINTS, ResourceType.COGNITION, ResourceType.MANPOWER] },
]

var amounts: Dictionary = {}  ## ResourceType (int) -> amount (float)
var income_per_month: Dictionary = {}  ## ResourceType (int) -> float (net per month, for top bar)


func _init() -> void:
	for r in range(ResourceType.LAST):
		amounts[r] = 0.0
		income_per_month[r] = 0.0


func get_amount(res: ResourceType) -> float:
	return amounts.get(res, 0.0)


func add_amount(res: ResourceType, delta: float) -> void:
	amounts[res] = amounts.get(res, 0.0) + delta
	amounts[res] = maxf(0.0, amounts[res])


func set_amount(res: ResourceType, value: float) -> void:
	amounts[res] = maxf(0.0, value)


func can_afford(costs: Dictionary) -> bool:
	for res in costs:
		if get_amount(res as GameResources.ResourceType) < (costs[res] as float):
			return false
	return true


func pay(costs: Dictionary) -> void:
	for res in costs:
		add_amount(res as GameResources.ResourceType, -(costs[res] as float))
